notaryproject/ratify

- README.md
- cmd/ratify/cmd/discover.go
- cmd/ratify/cmd/resolve.go
- cmd/ratify/cmd/root.go
- docs/store.md
- pkg/executor/core/executor.go
- pkg/executor/core/executor_test.go
- pkg/executor/core/testtypes.go
- pkg/ocispecs/descriptor.go
- pkg/referrerstore/api.go
- pkg/referrerstore/factory/factory_test.go
- pkg/referrerstore/mocks/types.go
- pkg/referrerstore/oras/oras.go
- pkg/referrerstore/plugin/const.go
- pkg/referrerstore/plugin/plugin.go
- pkg/referrerstore/plugin/plugin_test.go
- pkg/referrerstore/plugin/skel/skel.go
- pkg/referrerstore/plugin/skel/skel_test.go
- pkg/referrerstore/types/types.go
- pkg/referrerstore/utils/utils.go
- pkg/referrerstore/utils/utils_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- pkg/verifier/mocks/types.go
- pkg/verifier/plugin/plugin_test.go
- plugins/referrerstore/sample/sample.go
- Added a method in store interface to resolve tag to digest. Fixes #74 
- All stores are iterated till a store resolves the tag without any error. If all stores fail to resolve, error is returned.
- Updated tests and added new tests for this method
- Added a command ```resolve``` that can be to resolve the tag and for debugging purposes
- Updated the store specification with this new method.
- Updated readme.md to use ratify with $IMAGE
With this change, ratify can now be used to verify with tag
```bash
ratify verify -s $IMAGE
```
Signed-off-by: Tejaswini Duggaraju <naduggar@microsoft.com>
> Added resolving tag to digest in the store interface

- go.mod
- go.sum
- pkg/referrerstore/oras/oras.go
- Import oras library that has fix for authenticating a private registry.
- Remove dependency on crane for resolving the descriptor for a subject as Resolve is available in oras library
Signed-off-by: Tejaswini Duggaraju <naduggar@microsoft.com>
> Support private registry in oras

- charts/ratify/templates/deployment.yaml
- charts/ratify/templates/dockerconfigsecret.yaml
- cmd/ratify/cmd/discover.go
- pkg/referrerstore/oras/oras.go
- Added support for authenticating registries using Docker config
-  The helm install/upgrade command would be 
```bash
helm install ratify charts/ratify --set-file dockerConfig=<path to the local Docker config.json file>
```
- This will create a [Docker config](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials) k8s secret, mount the file to the ratify container and set the DOCKER_CONFIG
- If the env DOCKER_CONFIG is set, oras store will use it to authenticate the private registry if its credentials are configured in the docker config file.
Signed-off-by: Tejaswini Duggaraju <naduggar@microsoft.com>
> Add support for authenticating registries with Docker config

- charts/ratify/templates/deployment.yaml
- docs/private-registries.md
The PR #106  enables authentication to private registries using the local Docker config file. This PR extends this authentication by allowing customers to create the docker config secret from command line and use that secret to deploy Ratify. A document describing these details is also added to this PR.
Signed-off-by: Tejaswini Duggaraju <naduggar@microsoft.com>
> Added support to create docker config secret from command line

- pkg/referrerstore/oras/cosign.go
- pkg/referrerstore/oras/oras.go
This change fixes an issue with cosign manifest discovery and allows the oras referrerstore to be used for registries that only support cosign artifacts.
With the tag to digest implementation the subjectReference is now passed in with proper values to use directly with the cosign APIs and does not require this string check anymore.
When oras `Discover` is called it returns a 404 if the registry does not support oras endpoints. We check for the 404 and if cosign is enabled there is still a chance that cosign artifacts could be discovered in a later call. We log a message and allow the function to continue.
This change was tested against:
- Local registry with oras support and no artifacts
- Local registry with oras support and only cosign signatures
- Local registry with oras support, …
> Fix for cosign verifier

- charts/ratify/templates/_helpers.tpl
- charts/ratify/templates/akv-secret-provider.yaml
- charts/ratify/templates/deployment.yaml
- charts/ratify/templates/dockerconfigsecret.yaml
- charts/ratify/values.yaml
- Added support of Azure keyvault provider to secret store CSI driver in AKS. With this support, the notation certificate can be obtained from AKV certificate that gets mounted to the ```ratify``` container
- The AKV is accessed using the AAD pod identity in AKS. The necessary steps to setup all the required add-ons and the configuration to enable this access in the ratify is outlined in the [Hack doc](https://hackmd.io/OPhToZZaQ3K36hyy9jTy7g?both)
-  Addresses #76 where notation CLI can be used to perform remote signing and ```ratify``` can be used to perform local verification using ```notation``` libraries.
> Updates to deployment helm chart to support Certificate from Azure Key vault

- httpserver/handlers.go
- httpserver/server_test.go
- pkg/executor/core/executor.go
- pkg/executor/core/executor_test.go
- pkg/executor/core/testtypes.go
Fixes #92 
Root Cause:
- The Gatekeeper validating webhook timeout is set to 3 seconds while the current verification timeout is 8 seconds
- A longer running verification process will cause the Gatekeeper webhook to timeout and cancel the context
- The error will be emitted but code structure will short circuit to success. 
Solution: 
- Set timeout to be less than or equal to the webhook timeout (3 seconds). Verifier will timeout before webhook does and block the deployment as expected. 
Validation Steps:
1. Update notaryv2 plugin to sleep for time > 3 seconds
2. Attempt to deploy signed image. 
3. Deployment is blocked with error message: `Error from server ([ratify-constraint] Image verification failed : {"errors": [], "responses": [], "status_code": 200, "system_error": "validate …
> [Bugfix] Updating default timeout

- charts/ratify/templates/configmap.yaml
- config/config.go
- config/config.json
- pkg/referrerstore/oras/oras.go
This fixes an issue with creating the oras local cache directory in a distroless container image.
- Remove explicit `localCachePath` from the default `config.json`
- Update oras implementation to properly build the path for the `localCachePath`
- Fix an error message to properly display the path and error
Fixes #124
> Fix issue with oras local cache path

- pkg/referrerstore/oras/authprovider/k8secret_authprovider.go
- adds 12 hour expiration to kubernetes secret credential fetched
- cache will automatically refresh if secret credential is expired
> Add Kubernetes Secret Expiration

- docs/oras-auth-provider.md
- Adds documentation for ORAS Auth Provider
- Currently has user guides for default docker-config, azure workload identity, and k8s secrets
Should wait for #137 to be completed before merging
Closes #143 
Closes #144
> Add ORAS Authentication Provider Documentation 

- charts/ratify/templates/configmap.yaml
- charts/ratify/values.yaml
- add azure workload identity and k8s secrets auth providers in config map
- templatized so the provider used is determined by flags in values.yaml
> Adding Auth Provider Templates to Chart

- pkg/referrerstore/oras/oras.go
- Evicts the repository from the authentication cache if any of the ORAS operations returns a 401 error
- This allows for credential Provide process to re populate the cache the next retry
> Add Auth Cache Eviction

- pkg/verifier/api.go
- pkg/verifier/factory/factory_test.go
- pkg/verifier/notaryv2/notaryv2.go
- pkg/verifier/plugin/plugin.go
- The individual verifier report would fail to show `isSuccess` as false. This was due to the default false value being omitted in the JSON decoding process. Refer to https://github.com/golang/go/issues/13284 for Go encoding issue.
- Resolved by removing `omitEmpty` and adding isSuccess: false explicitly where it was missing
Partially Fixes #152
> Fix isSuccess not showing in output

- README.md
- charts/ratify-gatekeeper/values.yaml
- charts/ratify/templates/configmap.yaml
- cmd/ratify/cmd/serve.go
- update configmap, and README to set validating webhook timeout to 7 seconds
- add executor config to set timeout to 6800ms
Related Gatekeeper issue: https://github.com/open-policy-agent/gatekeeper/issues/1956
> Update validating webhook timeout to 7 seconds

- cmd/ratify/cmd/referrer.go
- docs/README.md
- go.mod
- go.sum
- pkg/referrerstore/api.go
- pkg/referrerstore/mocks/types.go
- pkg/referrerstore/oras/oras.go
- pkg/referrerstore/plugin/plugin.go
- pkg/referrerstore/plugin/plugin_test.go
- pkg/referrerstore/plugin/skel/skel.go
- pkg/referrerstore/plugin/skel/skel_test.go
- pkg/verifier/notaryv2/notaryv2.go
- plugins/referrerstore/sample/sample.go
- plugins/verifier/licensechecker/licensechecker.go
- plugins/verifier/sbom/sbom.go
- Use the `FetchReference` method in ORAS to fetch blob content
- Remove `blobDesc` parameter from referrer store API as it's redundant
- Update `getRawContentFromCache` to use `ioutil.ReadAll` to avoid relying on Descriptor `size`
> Use ORAS FetchReference

- charts/ratify/templates/akv-secret-provider.yaml
- charts/ratify/templates/deployment.yaml
- charts/ratify/values.yaml
update CSI driver to use also use workload identity so user won't have to configure workload identity as well as pod identity.
> CSI Driver template update for workload identity

- .github/workflows/publish-charts.yml
adding a workflow to publish helm chart as github page as suggested in https://github.com/deislabs/ratify/issues/85
This workflow will publish charts directory to default branch gh-pages
After merging this PR, a branch with name "gh-pages" needs to be created and configured as the github page branch.
Customer will be able to install ratify without cloning ratify repo. Sample commands below from testing with my fork:
helm repo add ratify https://susanshi.github.io/ratify
helm install ratify ratify/ratify --atomic
kubectl apply -f https://susanshi.github.io/ratify/charts/ratify-gatekeeper/templates/constraint.yaml
closes #85
> workflow to publish helm chart as github page

- .github/workflows/release.yml
- update go releaser.yml file to use 1.17
> Bump Releaser to Go 1.17

- charts/ratify/templates/configmap.yaml
- The config map's k8s secret auth provider name was incorrect. This PR updates to the correct name.
> [Bugfix] Update K8 Secret Auth Provider Name

- charts/ratify/templates/deployment.yaml
Added `.Values.serviceAccount.name` to be able to spec SA name in Deployment resource, without creating the SA. This will allow processes, outside of the helm chart, to create SA used by the helm chart.
Closes #207
> Fix for Issue 207 - spec SA by name

- charts/ratify/templates/configmap.yaml
- config/config.go
- config/config.json
- config/config_test.go
- docs/examples/ratify-on-aws.md
- docs/examples/ratify-verify-azure-cmd.md
- docs/oras-auth-provider.md
- docs/policy-provider.md
- docs/quickstart-cli.md
- docs/working-with-spdx.md
- pkg/referrerstore/factory/factory_test.go
- pkg/referrerstore/mocks/types.go
- pkg/referrerstore/oras/authprovider/authprovider.go
- pkg/referrerstore/oras/authprovider/authproviderfactory_test.go
- pkg/referrerstore/oras/authprovider/azure/azureworkloadidentity.go
- pkg/referrerstore/oras/authprovider/azure/azureworkloadidentity_test.go
- pkg/referrerstore/oras/authprovider/k8secret_authprovider.go
- pkg/referrerstore/oras/oras.go
- plugins/verifier/cosign/README.md
- Switch config to using camel case everywhere
- Switch highest level schema of JSON to be singular `stores` --> `store`, `policies` --> `policy`, `verifiers` --> `verifier`
Fixes #233 
> Fix Configuration File Inconsistencies

- .goreleaser.yml
Update go releaser yaml to user go mod tidy --compat=1.17
> Update go releaser template to use go mod tidy 1.17 compat

- .github/workflows/sync-gh-pages.yml
- Merges 'main' branch into 'gh-pages' branch on push to 'main' only when 'library/**' directory is changed
- NOTE: this will kick off a new gh page publish action every time a change to 'libary/**' folder is merged to main. NOT just on release.
Fixes #273 
- Tested with personal fork of Ratify and simulated push flow to library folder
> Add GH Page Sync Workflow

- Makefile
- config/config.json
- pkg/verifier/notaryv2/notaryv2.go
This change addresses some paper cuts with running ratify via the CLI and running the docker container by itself. A default notaryv2 certificate directory has been added at `~/.ratify/ratify-certs` so that ratify runs successfully when built from source using the default config.
Fixes #79 
> Add default path for notaryv2 certificates

- docs/quickstart-cli.md
Signed-off-by: Binbin Li <libinbin@microsoft.com>
Oras cli migrated oras push artifact to oras attach command. The quickstart-cli doc is not updated yet. Update the corresponding command in this PR.
Fixes https://github.com/deislabs/ratify/issues/297
> doc: update quickstart-cli to use oras attach instead of oras push

- docs/examples/ratify-verify-azure-cmd.md
- docs/quickstart-cli.md
- go.mod
- go.sum
- pkg/executor/core/executor.go
- pkg/utils/certificateUtils.go
- pkg/verifier/notaryv2/notaryv2.go
Signed-off-by: Binbin Li <libinbin@microsoft.com>
1. Bumped up notation-go from v0.8.0-alpha.1 to v0.11.0-alpha.4 and introduced dependency of notation-core-go of v0.1.0-alpha.4.
2. Update the usage of verifier from notation-go. Now the verifier supports both JWS and COSE envelopes now.
3. Update the quickstart-cli.md
Fixes https://github.com/deislabs/ratify/issues/350
> feat: bump notation-go from v0.8.0-alpha.1 to v0.11.0-alpha.4

- RELEASES.md
- httpserver/handlers.go
- httpserver/types.go
Adds a new type that represents the response for an http request. This type insulates the internal implementation from external consumers and adds a version field so that we can track changes that could break external consumers. For now the format of the response is still not that formally typed, but this gives a starting point.
Fixes #261 
> Add wrapper for http response with version

- charts/ratify/Chart.yaml
Signed-off-by: David Tesar <david.tesar@microsoft.com>
During the 1.1.0 release, we bumped the chart version to 1.1.0 and then in the next release bumped the chart version down to 1.0.0.  This makes helm deploy an older version of the released version of ratify.
> fix helm chart to be SemVer latest

- pkg/referrerstore/oras/oras.go
Fixes ORAS cache concurrency issue. ORAS error didn't match the error we were catching.
Fixes #391 
> Fix go concurrency ORAS cache bug

- charts/ratify/templates/configmap.yaml
- charts/ratify/templates/deployment.yaml
- charts/ratify/templates/secret.yaml
- docs/examples/ratify-on-aws.md
- pkg/referrerstore/oras/cosign.go
- pkg/verifier/notaryv2/notaryv2.go
- test/bats/tests/configmap/invalidconfigmap.yaml
Noel and Lachie reported an issue where notaryv2.go at VerificationCerts and will validate all of the paths against the notary v2 expectations (x509 certs). Since we pass in /usr/local/ratify-certs - that includes everything, both the ratify-test.crt (good!) as well as the cosign.pub file (not so good!), which is in PEM format.
This PR contains the following update:
- mounts cosign cert and notary cert in separate paths
- removing configmap policy so that when validation will pass if there is only one type of signature available
- fixing inconsistency for cosign artifactType
Fixes # (381)
Enabled Notary and Cosign in configuration, run kubectl run with the following image, 
1.Image with only notary signature, deployment was successful when …
> Chart updates to allow cosign and notary verifier to be configured together

- pkg/referrerstore/oras/oras.go
When using ratify with a registry that does not support the referrers API but we want verify Cosign signatures, verification process would fail since referrers API is queried first and a 404 is returned from registry. This fix catches the error and continues.  This follows the original approach we used before we upgraded ORAS to v2. 
This will unblock ECR cosign walk through and using GCR
> [Bugfix] Fix ECR and GCR support with Cosign Signatures

- CONTRIBUTING.md
Sample command for mTLS documentation is missing a `\` in the command.
While testing mTLS, encountered a missing `\` in the sample helm install command.
> Fix mTLS documentation

- charts/ratify/templates/store.yaml
- cmd/ratify/cmd/serve.go
- config/samples/config_v1alpha1_verifier_cosign.yaml
- pkg/controllers/store_controller.go
- pkg/controllers/verifier_controller.go
- pkg/manager/manager.go
- pkg/verifier/factory/factory.go
- test/bats/test.bats
Following issues are fixed in the Crd code path:
- The Crd code path was not setting the default plugin path
- Start Server should take in config path
- remove '-' in Cosign property from oras template
> Bugfix: set default path for plugin in Crd code path

- charts/ratify/templates/akv-secret-provider.yaml
- charts/ratify/templates/configmap.yaml
- charts/ratify/templates/deployment.yaml
- charts/ratify/templates/provider.yaml
- charts/ratify/values.yaml
Chart update to support Azure MSI as oras auth provider.
Chart update to support AKV cert from multiple keyvault and certs
Fixes # 314
> Update chart to support azure msi oras auth provider

- charts/ratify/values.yaml
For security reasons, we should not pile on to the default service account ,we should create a default ratify service account.
The following roles are assigned to the Ratify service account. 
[ClusterRole,secret-reader][ClusterRole,ratify-manager-role]
Fixes # 412
Validated with quick start steps.
> bugfix: set ratify default sevice account

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/config.default.json
- .devcontainer/devcontainer.json
- .devcontainer/gatekeeper.http
- .devcontainer/post-create.sh
- .gitignore
- .vscode/launch.json
- Updates the devcontainer to work with the latest toolchain (ORAS `0.16.0`, notation `1.0.0-rc1`, etc)
- Adds VS Code debug config
- Automatically configure Ratify for use with the image used in the quick start (`wabbitnetworks.azurecr.io/test/notary-image:signed`)
- README in `.devcontainer` updated
> Update devcontainer for latest Ratify

- pkg/referrerstore/plugin/plugin.go
- pkg/verifier/plugin/skel/skel.go
- pkg/verifier/plugin/skel/skel_test.go
- Enables verifier plugins to consume `pluginBinDirs` from STDIN and use them to resolve store plugins
- Adds tests to validate that the path is used
- Adds test coverage to ensure that builtin stores are correctly resolved
Fixes #492
> Enable verifier plugins to work with store plugins

- api/v1alpha1/groupversion_info.go
- pkg/referrerstore/oras/authprovider/authprovider.go
- pkg/referrerstore/oras/authprovider/k8secret_authprovider.go
- pkg/referrerstore/oras/oras.go
- pkg/verifier/notaryv2/notaryv2_test.go
Adds the results after running `make build`, which includes `go fmt ./...`
Just a small update so that whitespace changes in these files don't add noise during dev
> chore: go fmt

- config/config.json
- docs/README.md
- docs/reference/gatekeeper-policy-authoring.md
- httpserver/server_test.go
- pkg/executor/config/config.go
- pkg/executor/core/executor.go
- pkg/executor/core/executor_test.go
Removes passthrough mode, per #474
Cleans up docs & references to the feature
In addition to the discussion in the issue, I discovered that execution mode was never set to passthrough in the Helm chart, so I believe this should affect no one, as everyone has been using Gatekeeper + Rego without passthrough mode all along. See https://github.com/deislabs/ratify/blob/main/charts/ratify/templates/configmap.yaml
Fixes #474
- Probably worth a mention in the next release notes + community call. That said, I don't think it affects anyone unless they were manually hacking the Helm chart configmap post-render or …
> Remove executionMode (passthrough mode)

- .vscode/launch.json
- cmd/ratify/cmd/root.go
- docs/README.md
- docs/reference/usage.md
- pkg/common/logging.go
- pkg/common/logging_test.go
- pkg/common/plugin/exec.go
- pkg/controllers/store_controller.go
- pkg/controllers/verifier_controller.go
- pkg/manager/manager.go
As part of plugin development, I'd like to be able to turn on some `DEBUG` logs so I can see what's actually being passed into my plugin, but I don't want to spam users with verbose info at runtime. Ratify currently defaults to the `INFO` log level, and it's not configurable. Other folks have asked for this as well in the issues
* Implements configurable log levels via `RATIFY_LOG_LEVEL`, with the default to the current `INFO` level
* Adds tests for the above
* Adds a new "usage" docs page that documents the `RATIFY_*` environment variables
* Adds debug logging for plugin executables
> Note: I believe it could be valuable to have Cobra-generated markdown docs, and/or add robust documentation for the other env vars that are in use, particularly around auth stores (ex: `AWS_REGION`, …
> Add configurable logging level

- .github/workflows/build-pr.yml
The github build workflow currently does not get triggered for Pull Requests that only have changes to markdown files. This then blocks the PR from merging since build-pr is a required check. 
This change removes the markdown file bypass.
ORAS CLI repository also does not have a bypass for markdown file. See here: https://github.com/oras-project/oras/blob/a671c16f2dc788699e355dbb2019740ef72f8107/.github/workflows/build.yml#L14
Fixes #
> ci: remove markdown file bypass

- .github/workflows/build-pr.yml
- Makefile
- README.md
- charts/ratify/templates/deployment.yaml
- charts/ratify/templates/provider.yaml
- charts/ratify/values.yaml
- httpserver/server.go
As Gatekeeper v3.11.0 comes out, Ratify needs to bump external data to v1beta1 and use TLS/mTLS. To be consistent with GK, Ratify will support the latest 2 versions, which are 3.10.0 and 3.11.0 for now.
This PR just add a make target to generate TLS certs/keys. There will be a following PR to add a helm hook to automate the generation.
We have a issue: https://github.com/deislabs/ratify/issues/529 to track the upgrade.
e2e tests.
Tested manually in gatekeeper-system namespace, which picked up the cert and set mTLS successfully.
> ci: add gatekeeper version matrix

- pkg/executor/core/executor.go
- pkg/executor/core/executor_test.go
- pkg/executor/core/testtypes.go
- pkg/referrerstore/mocks/memory_store.go
- pkg/verifier/api.go
- pkg/verifier/factory/factory_test.go
- pkg/verifier/notaryv2/notaryv2.go
- pkg/verifier/notaryv2/notaryv2_test.go
- pkg/verifier/plugin/plugin.go
- pkg/verifier/plugin/plugin_test.go
This PR moves the nested references logic out of plugins and into the executor while keeping the `nestedReferences` config values with Verifiers. There is no effective behavior change but it provides a clearer code execution. This lays out the initial changes for [decoupling nested references from verifiers](https://github.com/deislabs/ratify/issues/528)
- Moves verifying nested references out of `pkg/verifier/plugin/plugin.go` and into `pkg/executor/core/executor.go`
- Removes executor from `Verifier.Verify()`
- adds `GetNestedReferences` method for verifiers
- notary signature verifier method returns empty slice because signatures should not check nested references 
- adds tests for nested references
- `TestVerifySubject_NoNestedReferences_Expected`
- …
> feat: move nested reference logic to executor (keep config w/ verifiers)

- charts/ratify/templates/deployment.yaml
- charts/ratify/values.yaml
- cmd/ratify/cmd/serve.go
- httpserver/cache.go
- httpserver/handlers.go
- httpserver/server.go
- httpserver/server_test.go
- pkg/manager/manager.go
- test/bats/test.bats
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
- Adds request cache lock to enable processing verification once per subject in case of concurrent requests. The verification results are cached with a 5min TTL and refreshed if the cache entry is expired at read time. 
Fixes #507 
> feat: add request cache lock for verification

- pkg/utils/utils.go
- pkg/utils/utils_test.go
- Adds `docker.io/library` prefix if domain not present in subject reference
- This is consistent with expected behavior from Docker and other derived tooling
- Add unit tests
Fixes #591
> fix: add docker domain prefix as default

- charts/ratify/templates/deployment.yaml
Adds the required pod label for [Azure Workload Identity](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html) when the corresponding Helm value is enabled
Handles the immediate blocker for #629, but doesn't address the further discussion points in the issue
> fix: add pod label for workload identity

- plugins/verifier/cosign/cosign.go
- Removes the auth provider field in cosign
- This field was never used and a new change to the name in the struct caused a type mismatch when deserializing.
Fixes #655 
- All Azure tests pass on local fork
> fix: remove unused authProvider field in cosign verifier

- Makefile
- Recent changes to Notation CLI have changed default referrer manifest from OCI Artifact to OCI Image
- There are some critical bugs in the notation v2 verifier implementation in ratify that need to be address before full OCI Image support.
- This change pins the notation version used in test to a specific version (1.0.0-rc.2 notation for now)
Fixes #
> fix: pin notation to specific version in e2e test

- Makefile
- pkg/ocispecs/descriptor.go
- pkg/referrerstore/oras/oras.go
- pkg/referrerstore/oras/utils.go
- pkg/referrerstore/oras/utils_test.go
- pkg/verifier/notaryv2/notaryv2.go
- plugins/verifier/cosign/cosign.go
- plugins/verifier/licensechecker/licensechecker.go
- plugins/verifier/schemavalidator/schema_validator.go
- test/bats/cli-test.bats
- test/bats/test.bats
Most verifiers rely on the Blobs field to enumerate the content of each artifact. This field is populated directly from the manifest byte marshalling. In the case of an OCI Image referrer, this marshalling will not populate Blobs causing all other verifiers to prematurely finish before any content is verified. This PR:
- Updates ReferenceManifest to use `Blobs` and adds logic in ORAS store to marshal Layers/Blobs to the `Blobs` field depending on the referrer media type.
- Updates Notaryv2 verifier to check for 0 length blob array and fail if no signatures found
- Updates Cosign verifier to use `Blobs` field
TODO: Add e2e test with OCI Image and OCI Artifact as referrer manifest type
Fixes #
Please describe the tests that you ran to verify your …
> feat: support OCI Image

- charts/ratify/templates/inline-certificate-provider.yaml
The latest helm deployment with Ratify expects notaryCert which is used to pass the public key for Notary verifications as mandatory which is not as expected since Ratify can  be used for other use cases like cosign verification and aggregator 
where it is not necessary.
fixes #713 
Bug fix
Did a helm deploy from local chart without notary cert param and it passed
helm install ratify \
ratify/ratify --atomic
--namespace gatekeeper-system --set-file cosign.key=./cosign.pub --set-file dockerConfig=./config.json
> fix: make notary cert optional rather than mandatory since it is not always required in helm ratify deploy

- pkg/metrics/prometheus_exporter_test.go
The prometheus exporter test starts up a local server for testing. This server can take time to start up and exists in the same context as the requests being sent to it. As a result, there can be some runs when the server is not ready in time to accept requests causing test flakiness. This PR adds a 2 second delay for server initialization buffer. 
> fix: add time delay for prometheus exporter test

- charts/ratify/templates/akv-certificate-provider.yaml
- charts/ratify/templates/inline-certificate-provider.yaml
- charts/ratify/templates/store.yaml
- charts/ratify/templates/verifier.yaml
Add pre-install hook to CR templates so that they could be skipped rendering and only be installed after CRDs are updated.
Fixes https://github.com/deislabs/ratify/issues/765
Tested locally with v1alpha1 CRDs, the new chart could be deployed successfully with CRDs upgraded to v1beta1.
> feat: add pre-install hook to Ratify CRs

- .github/workflows/build-pr.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- .gitignore
- Makefile
- go.mod
- httpserver/Dockerfile
Upgrade go version to 1.20 to leverage coverage profiling support for integration tests.
This PR doesn’t make a big difference in the test coverage, but it adds 600 more lines to the reports.
Fixes #791 
Test coverage breakdown in main branch: 
Test coverage breakdown in this PR:
> feat: upgrade go to 1.20 to use coverage profiling for integration tests.

- api/unversioned/certificatestore_types.go
- api/v1alpha1/zz_generated.conversion.go
- api/v1beta1/certificatestore_types.go
- api/v1beta1/zz_generated.conversion.go
- charts/ratify/crds/certificatestore-customresourcedefinition.yaml
- config/crd/bases/config.ratify.deislabs.io_certificatestores.yaml
- pkg/controllers/certificatestore_controller.go
- pkg/controllers/certificatestore_controller_test.go
Add truncated error message to CertificateStore Status to avoid displaying long error message when listing it.
Fixes #843 
Status before:
Status after:
Details when describing it:
> feat: add brief err to CertificateStore CRD

- Makefile
> test: testscript change echo file to printf

- Makefile
- httpserver/Dockerfile
- test/bats/base-test.bats
- test/bats/plugin-test.bats
1. Update Dockerfile so that it can select which external plugin to be built. The default building will just include notation verifier.
2. Split test.bats to base_test and plugin_test. base_test will cover test cases running on image with built-in notation verifier. plugin_test will cover test cases for each added external plugin. Notes: the original test will be deleted in a following PR.
Fixes https://github.com/deislabs/ratify/issues/858
e2e test passed.
> build: build external plugins conditionally

- Makefile
As this issue mentioned, the latest release is missing linux-x64 build which is breaking our pipeline. https://github.com/microsoft/sbom-tool/issues/271 We can see if sbom-tool could fix it soon and keep this PR open. Otherwise we can merge this PR as a workaround to fix the pipeline.
Fixes #
> fix: switch to working version of sbom-tool

- .github/workflows/publish-package.yml
We updated the build step to optionally build the plugin, see PR [860], (https://github.com/deislabs/ratify/pull/860/files#diff-9c427950275d8aad2e8016fd20f5615c15acda7205793165fe31d45748ee0e9d), but our publish workflow is not currently passing in of the params.
The immdiate fix , we need to update our publish workflow to build ratify image with the plugin.  We also have a test gap here , we should also have test run against latest released version
Fixes # 915
> fix: publish ratify image with plugin 

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
Signed-off-by: Yi Zha <yizha1@microsoft.com>
The `triage` label indicates the issue or PR needs triage. This PR adds `triage` label for a newly created issue, since every new issue needs to be triaged. Once an issue is triaged, we can then remove the `triage` label. With this label and process, it will improve the efficiency of our issue management. For example, we can easily filter out all the issues that are not triaged.
Fixes #
> chore: add triage label to issue template

- charts/ratify/templates/assign.yaml
- charts/ratify/templates/provider.yaml
- charts/ratify/values.yaml
- httpserver/handlers.go
Allow image mutation to be optional in helm chart. This change introduces one new property in helm chart under provider.
`provider.enableMutation=true`
When `provider.enableMutation` is set to false, it disables creation of
1. All mutation assign CRDs
2. ratify-mutation provider CRD
Current ratify helm chart allows image mutation by default. All image tags are replaced with image digest. This may not be desirable in some use cases. E.g. if there are OPA gatekeper constraints based on image tags or if the image tags reflects application revision.
Fixes #943 
> feat: optional image mutation in helm chart

- charts/ratify/Chart.yaml
- charts/ratify/values.yaml
- helmfile.yaml
- high-availability.helmfile.yaml
- bump chart versions to rc7
- bump versions in helmfiles to 1.9.0
- add mandatory CERT_ROTATION feature flag to helmfiles. 
Fixes #
> chore: prepare rc7 release

- .github/workflows/publish-package.yml
- httpserver/Dockerfile
- internal/version/version.go
- pkg/common/plugin/download.go
- pkg/referrerstore/oras/oras.go
Add version and OS/Arch info to the user-agent header.
Fixes https://github.com/deislabs/ratify/issues/1040
Manually built image with `v1.0.0` tag and added a test log before setting the user-agent.
> feat: add version and OS/Arch to user-agent header

- RELEASES.md
- charts/ratify/Chart.yaml
- charts/ratify/values.yaml
- dev.helmfile.yaml
- dev.high-availability.helmfile.yaml
- helmfile.yaml
- high-availability.helmfile.yaml
> feat: update chart for rc8

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Resolved error when trying to launch the project in dev container
- Added write permission of /go/pkg to non-root user `vscode`
- Upgraded Go version of the dev container from 1.19 --> 1.20
Fixes #1142 
> chore: upgrade devcontainer config

- charts/ratify/Chart.yaml
Add icon to helm chart so that it could be displayed on ArtifactHub.
Fixes #
> chore: add chart icon

- dev.helmfile.yaml
- dev.high-availability.helmfile.yaml
- updates the dev helmfiles to use version 1.12.0 which is the v1.1.0 chart version equivalent. This was accidentally missed during release
Fixes #
> fix: bump dev helmfile ratify chart versions

- .github/workflows/build-pr.yml
update log name
we are running into name conflicts on log upload in the Main Branch. Sample run : https://github.com/deislabs/ratify/actions/runs/7382498997/job/20082364247
This PR appends aks to aks log name so it doesn't conflict with e2e log name.
Fixes #
- [X ] Bug fix (non-breaking change which fixes an issue)
> fix: differentiate aks logs from e2e log 

- .github/workflows/build-pr.yml
Currently we use `continue-on-error` to prevent cancelling due to failed job. But it will make the overall workflow ignore those failing jobs and report OK like the screenshot:
Switching to use `strategy.fail-fast` to prevent cancelling but report failure to the overall result.
After the change:
Fixes #
> ci: switch to fail-fast from continue-on-error

- pkg/controllers/store_controller_test.go
- pkg/controllers/verifier_controller_test.go
- pkg/referrerstore/factory/factory_test.go
- pkg/referrerstore/plugin/skel/skel_test.go
- pkg/utils/test_utils.go
- pkg/verifier/factory/factory_test.go
- pkg/verifier/plugin/skel/skel_test.go
Fix unit tests that are failing due to missing plugin binaries in local environment.
Fixes #
> fix: fix unit tests that fail in local environment

- httpserver/handlers.go
- internal/context/utils.go
- internal/context/utils_test.go
This is the first PR for multi-tenancy support.
1.  Add a `GetNamespace` util method. It fetches the namespace embeded in the context. For each request, we'll use `SetContextWithNamespace` to embed the namespace into the context, and consumers like executors, verifiers, policyEnforcers could get the namespace from the context instead of passing it through function param explicitely.
2. Embed the namespace into the context for mutation requests as well.
Fixes #
> feat: add GetNamespace utils method for context [multi-tenancy PR 1]

- ADOPTERS.md
- CODE_OF_CONDUCT.md
update COC and add adopters.md to meet the CNCF donation criteria
Fixes #1334 
Doc
> docs: update COC and add adopters.md

- .github/workflows/e2e-cli.yml
- .github/workflows/pr-to-main.yml
- README.md
- go.mod
- go.sum
Reverts deislabs/ratify#1368
I need to revert this commit as this commit incorrectly squashed commits.
> Revert "chore: Bump actions/checkout from 4.1.1 to 4.1.2"

- pkg/controllers/resource_map.go
- pkg/controllers/store_controller.go
- pkg/controllers/store_controller_test.go
- pkg/customresources/referrerstores/api.go
- pkg/customresources/referrerstores/stores.go
- pkg/customresources/referrerstores/stores_test.go
- pkg/manager/manager.go
This is the 4th PR for multi-tenancy support. Please review https://github.com/deislabs/ratify/pull/1359 first. Check diff between PR 3 and PR 4 at: https://github.com/binbin-li/ratify/pull/117
1. Add a ReferrerStoreManager interface to wrap operations on namespaced store resources.
2. Update store references to use the new ReferrerStoreManager interface instead of directly accessing stores.
3. Move the `StoreMap` under controllers to resource_map.go so that it can be shared by clustered and namespaced controllers in the future.
4. Updated unit tests. Some unit tests are not added in this PR as we'll change the behavior soon.
5. For the interface implementation, it's in a transition stage that keeps the old behavior. Will update the implementation once Ratify fully supports multi-tenancy. …
> feat: add ReferrerStoreManager interface to wrap operations on namespaced stores [multi-tenancy PR 4]

- docs/design/Azure Kubernetes Workload Identity AuthProvider.md
- pkg/controllers/certificatestore_controller.go
- pkg/controllers/policy_controller.go
- pkg/controllers/resource_map.go
- pkg/controllers/store_controller.go
- pkg/controllers/store_controller_test.go
- pkg/controllers/utils/cert_store.go
- pkg/controllers/utils/cert_store_test.go
- pkg/controllers/verifier_controller.go
- pkg/controllers/verifier_controller_test.go
- pkg/customresources/certificatestores/api.go
- pkg/customresources/certificatestores/certificatestores.go
- pkg/customresources/certificatestores/certificatestores_test.go
- pkg/manager/manager.go
- pkg/verifier/notation/notation.go
- pkg/verifier/notation/truststore.go
This is the 5th PR for multi-tenancy support. Please review https://github.com/deislabs/ratify/pull/1380 first. Check diff between PR 4 and PR 5 at: https://github.com/binbin-li/ratify/pull/120
1. Add a CertStoreManager interface to wrap operations on namespaced certStore resources.
2. Update certStore references to use the new CertStoreManager interface instead of directly accessing cert stores.
3. Move the `CertificatesMap` under controllers to resource_map.go so that it can be shared by clustered and namespaced controllers in the future.
4. Updated unit tests. Some unit tests are not added in this PR as we'll change the behavior soon.
5. For the interface implementation, it's in a transition stage that keeps the old behavior. Will update the implementation once Ratify fully supports …
> feat: add certStoreManager interface to wrap operations on namespaced certStores [multi-tenancy PR 5]

- charts/ratify/templates/verifier.yaml
- test/bats/azure-test.bats
- test/bats/tests/config/config_v1beta1_verifier_cosign_akv.yaml
AKS test is failing due to `trust policy not found` error. Root cause is we missed a check on akv keys in verifier-cosign template.
And azure-test.bats would upgrade ratify deployment which might miss the azurekeyvault.keys in the template. https://github.com/binbin-li/ratify/blob/dev/test/bats/azure-test.bats#L29
The aks test is passing on my forked branch. 
Fixes #
> fix: add akv keys check on cosign-verifier

- pkg/verifier/cosign/cosign.go
- pkg/verifier/cosign/cosign_test.go
Updates the cosign.go parameter validation logic to create a verifier even if legacy config (`key` & `rekorURL`) is not provided AND trust policies are not defined. This is particularly necessary since helm chart will by default apply cosign verifier even if keys are not provided. 
Fixes #
> fix: handle empty trust policies

- .devcontainer/Dockerfile
Fixing 2 code scanning alerts that unpinned packages were installed. Just realized that we don't follow the semantic versioning while downloading the package.
Tested on my forked repo, which works as expected.
Fixes #
> chore: use semantic version for go install pkg

- charts/ratify/templates/akv-key-management-provider.yaml
AKS test is failing due to KMP not found error.
This PR updated the kind of `kmprovider-akv` from `NamespacedKeyManagementProvider` to `KeyManagementProvider` as the cluster-wide KMP is the default one.
AKS test passed on my forked repo: 
Fixes #
> fix: fix AKS test by switching to cluster-wide KMP

- charts/ratify/templates/inline-key-management-provider.yaml
We use range operator to iterate through `cosignKeys` and `notationKeys` to populate a series of KMPs. But we miss the separator in the range block which would only render the last KMP in each loop. Adding the separator to fix the problem.
The install command I tested:
```
noglob helm install ratify \
./charts/ratify --atomic \
--namespace gatekeeper-system \
--set image.pullPolicy=Always \
--set-file cosignKeys[0]="./test1.pub" \
--set-file cosignKeys[1]="./test2.pub" \
--set-file notationCerts[0]="./test/testdata/notation.crt" \
--set-file notationCerts[1]="./test/testdata/notation.crt" \
--set featureFlags.RATIFY_CERT_ROTATION=true
```
Screenshot before the change:
Screenshot after the change:
Fixes #
Please describe the tests that you ran …
> fix: fix missing separator in helm template

- charts/ratify/templates/verifier.yaml
- pkg/controllers/utils/verifier.go
- removes extra logging statement added during development
- updates cosign verifier helm chart template to specify a well-known path for `key` field. The cosign verifier expects an absolute file path in the `key` field and not the contents directly. This is because the value `cosign.key` passed in via helm chart is translated to a secret that is then mounted to a well known path in the Ratify container. Cosign verifier loads this key directly via a file path provided in the `key` field. This behavior is the legacy one but for backwards compatibility we must support it.
Fixes #
- locally installed v1.1.1 using …
> fix: update cosign chart and remove extra logs

- plugins/verifier/sbom/testdata/osv-scanner.toml
- plugins/verifier/schemavalidator/schemavalidation/testdata/osv-scanner.toml
- plugins/verifier/vulnerabilityreport/schemavalidation/testdata/osv-scanner.toml
- test/testdata/osv-scanner.toml
- updates osv scanner toml to ignore busybox vuln CVE-2023-42366. Busybox of the affected version is not used functionally in Ratify. Test SBOM + vulnerability report data contains it.
Fixes #
> chore: ignore CVE-2023-42366

- plugins/verifier/sbom/testdata/osv-scanner.toml
- plugins/verifier/schemavalidator/schemavalidation/testdata/osv-scanner.toml
- plugins/verifier/vulnerabilityreport/schemavalidation/testdata/osv-scanner.toml
- test/testdata/osv-scanner.toml
Ignores the CVE-2023-42363 CVE-2023-42364 CVE-2023-42365 vulnerabilities which affect busybox. Busybox at this affected version is not functionally used by Ratify but instead exists as part of test data (sboms, vuln reports, etc). 
Fixes #
> chore: ignore CVE-2023-42363 CVE-2023-42364 CVE-2023-42365

- .github/workflows/e2e-aks.yml
Remove `Update az cli` step in aks test since we no longer need it.
Tested on my forked repo
Fixes #
> fix: remove Update az cli step in aks test

- .github/workflows/e2e-aks.yml
- Makefile
- scripts/azure-ci-test.sh
- scripts/create-azure-resources.sh
- CI's currently rely on azure keyvault access policies which is now deprecated. Now, new KV by default only enable RBAC for permissions. Ratify needs to switch CI to use RBAC for secret fetch, key fetch, and key create. 
- workload identity is no longer a preview feature for AKS so preview extension is not necessary. this is now removed. 
Fixes #
> ci: switch azure ci test to use rbac for key vault access

- .github/workflows/clean-dev-package.yml
1. Add a job to delete dev package versions before releasing. It will keep the latest 7 versions which is the tagged version and its untagged multi-arch versions.
2. I made it only triggered manually. 
3. There are 2 reasons I don't add it as release step: 1) This action can delete at most 100 versions one time, so I need to run it several times to clean up all versions. 2) It's not fully tested as a stable option.
I tested on my forked repo, which keeps the latest 7 versions.
Fixes #
> ci: add job to delete dev package versions

- docs/proposals/Automated-Certificate-and-Key-Updates.md
This is the proposal for issue https://github.com/deislabs/ratify/issues/1131
> docs: add a proposal for periodic retrieval

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/dependabot.yml
- .github/workflows/build-pr.yml
- .github/workflows/codeql.yml
- .github/workflows/e2e-aks.yml
- .github/workflows/e2e-cli.yml
- .github/workflows/e2e-k8s.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/high-availability.yml
- .github/workflows/quick-start.yml
- .github/workflows/release.yml
- .github/workflows/run-full-validation.yml
- go.mod
- httpserver/Dockerfile
- upgrade all workflows and dockerfiles to go 1.22
Fixes #
> chore: upgrade to go 1.22

- docs/proposals/Release-Supply-Chain-Metadata.md
This pull request introduces significant changes to the `docs/proposals/Release-Supply-Chain-Metadata.md` file, outlining a comprehensive plan for improving the integrity and verifiability of Ratify's release assets. Key changes include proposals for signing all container images and binaries, generating Software Bill of Materials (SBOMs) for all assets, and publishing provenance information for each binary. The changes are organized into two stages of implementation and a future "to be determined" stage.
Fixes #
> docs: add proposal for producing supply chain metadata for all ratify assets

- .github/workflows/build-pr.yml
- .github/workflows/e2e-cli.yml
- .github/workflows/run-full-validation.yml
Secrets should be passed to reusable workflows. Currently we are missing the CODECOV_TOKEN while uploading to codecov. 
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
Fixes #
> fix: pass CODECOV_TOKEN to reusable workflow

- httpserver/types.go
- httpserver/types_test.go
- pkg/executor/core/executor.go
- pkg/verifier/api.go
- pkg/verifier/cosign/cosign.go
- pkg/verifier/cosign/cosign_test.go
- pkg/verifier/notation/notation.go
- pkg/verifier/types/types.go
This PR is part of effort for addressing https://github.com/ratify-project/ratify/issues/1654
1. Add `VerifierType` and `VerifierName` to replace `type` and `name`.
2. Add `ErrorReason` field to indicate root cause of an error.
3. Add `Remediation` field to include trouble shooting guide for the error.
4. Fixed a bug that missing `Subject` value in verifier report when using config policy.
5. Add `ReferenceDigest` to the verifierReport in V0 which is used by config poliy.
This PR does not change the usage of verification response, so the verifier report should look the same as before. We'll have separate PRs to update report generation logic to carry above values.
Fixes https://github.com/ratify-project/ratify/issues/1654
Please describe the …
> feat: Add more fields to verification response

- cmd/ratify/cmd/cmd_test.go
- errors/types.go
- errors/types_test.go
- test/bats/plugin-test.bats
This PR will refactor the message format returned by Error(). The new format is following the proposed improvement from https://github.com/ratify-project/ratify/pull/1662
Note: this pr is based on https://github.com/ratify-project/ratify/pull/1671, please check the actual diff at: https://github.com/binbin-li/ratify/pull/209
In general, for a nested Ratify error, we'll return a message in format:
`<Error Code>: <Error Description>: <Error Reason>: <Remediation>`,
where `Error Code` is the error code of the root error,
`Error Description` is concatenated details of all nested errors,
`Error Reason` is the detail or original error of the root error,
and `Remediation` is the remediation of the root error.
Let's take the below nested error as example:
```
{
Code: "TOP_ERR_CODE",
Detail: "top …
```
> feat: refactor error message format

- library/default/template.yaml
Reverts ratify-project/ratify#1732
It's currently blocking the quick-test job as Ratify v1.2 does not support exporting traceID and Time
> fix: Revert "chore: update default constraint template"

- pkg/referrerstore/oras/mocks/oras_storage.go
- pkg/referrerstore/oras/oras.go
- pkg/referrerstore/oras/oras_test.go
- pkg/verifier/notation/notation.go
- pkg/verifier/notation/notation_test.go
1. A quick fix to enforce validation on the Notation signature blob number. There should be exactly 1 blob in the manifest.Blobs which is also validated in Notation-go: https://github.com/notaryproject/notation-go/blob/8e2131d192fdb71c5268f81b4b9b93069559d3b5/registry/repository.go#L198
2. Remove critical cache failure in oras `GetReferenceManifest`
Fixes #
> fix: Enforce validation on notation signature blob number

- config/samples/clustered/verifier/config_v1beta1_verifier_notation_kmprovider.yaml
- config/samples/namespaced/verifier/config_v1beta1_verifier_notation_kmprovider.yaml
- library/multi-tenancy-validation/template.yaml
Recently we made a change to how verifier references a KMP: https://github.com/ratify-project/ratify/pull/1710
Previously we would just ignore a nonexistent KMP in verifier, after this PR, we would return the error indicating the misconfiguration in verifier config.
This PR removes unused KMP from the sample verifier which is referenced in azure-test. And update the constraint template so that it will report the traceID to help us debug in dumped log.
It already passed on my forked repo: 
Fixes #
> fix: remove nonexistent KMP from verifier sample

- pkg/referrerstore/oras/mocks/oras_storage.go
- pkg/referrerstore/oras/oras.go
- pkg/referrerstore/oras/oras_test.go
In a previous [PR](https://github.com/ratify-project/ratify/pull/1726), we have removed critical cache failure in oras `getReferenceManifest` method.
This PR will address the same issue in the `GetBlobContent` method.
And added more unit tests to fully cover both methods.
Fixes https://github.com/ratify-project/ratify/issues/1741
> fix: remove critical cache failure in oras `GetBlobContent`

- errors/pluginerrors.go
- errors/types.go
- errors/types_test.go
- internal/constants/constants.go
- pkg/controllers/clusterresource/policy_controller.go
- pkg/controllers/clusterresource/policy_controller_test.go
- pkg/controllers/clusterresource/store_controller.go
- pkg/controllers/clusterresource/store_controller_test.go
- pkg/controllers/clusterresource/verifier_controller.go
- pkg/controllers/clusterresource/verifier_controller_test.go
- pkg/controllers/namespaceresource/certificatestore_controller_test.go
- pkg/controllers/namespaceresource/policy_controller.go
- pkg/controllers/namespaceresource/policy_controller_test.go
- pkg/controllers/namespaceresource/store_controller.go
- pkg/controllers/namespaceresource/store_controller_test.go
- pkg/controllers/namespaceresource/verifier_controller.go
- pkg/controllers/namespaceresource/verifier_controller_test.go
- pkg/keymanagementprovider/refresh/kubeRefresh.go
- pkg/keymanagementprovider/refresh/kubeRefreshNamespaced.go
- pkg/keymanagementprovider/refresh/kubeRefreshNamespaced_test.go
- pkg/keymanagementprovider/refresh/kubeRefresh_test.go
The PR will address the issue that brief error is too short. Basically, the brief error will just contain the error code and root cause. And if it exceeds the max length(150 charactoers), the brief error will be truncated.
1. Add a new `GetConciseError` method to custom error to create an error message consisting of the error code and reason.
2. Update all controllers to use the new `GetConciseError` method to assign brief error value.
3. Set the maxLength from 30 to 150.
Examples:
Screenshot for Policy CR:
Screenshot for Verifier CR:
Screenshot for KMP CR:
Fixes https://github.com/ratify-project/ratify/issues/1453
> feat: enhance CR status with clearer brief error message

- scripts/azure-ci-test.sh
- test/bats/azure-test.bats
End to end tests that validate the KMP refresh feature.
Fixes #
> test: e2e tests for kmp refresh logic

- pkg/verifier/notation/notation.go
- test/bats/tests/config/config_v1beta1_verifier_notation.yaml
Showing verifier config parse error about using `VerificationCertStores` in mixed format in err log
Before:
Screen Capture
Details
```
time=2024-09-10T12:50:33.130136555Z level=debug msg=creating notation with config map[artifactTypes:application/vnd.cncf.notary.signature name:verifier-notation trustPolicyDoc:map[trustPolicies:[map[name:default registryScopes:[*] signatureVerification:map[level:strict] trustStores:[ca:ca-certs] trustedIdentities:[*]]] version:1.0] type:notation verificationCertStores:map[ca:map[ca-certs:[certstore-inline]] certs:[ratify-notation-inline-cert]]], namespace '' component-type=verifier go.version=go1.21.10
time=2024-09-10T12:50:33.130257057Z level=error msg=Error: config invalid, Code: CONFIG_INVALID, Plugin Name: …
```
> fix: showing verifier config parse detail in err log

- docs/design/kmp-nversions.md
Design document for nVersionCount support for the KMP.
> docs: nVersionCount support for KMP design doc

- .github/workflows/publish-package.yml
Fixing a bug in publish-ghcr workflow that does not tag the release correctly. 
Validated the fix in my forked repo:
Before the PR, the ratify useragent is like ratify+(commit sha)
Fixes #
> ci: fix tagging in publish-ghcr workflow

- .github/workflows/scan-vulns.yaml
Revert to use trivy CLI directly and add retry logic to mitigate DB download failure.
Fixes #
> ci: retry trivy download-db on failure

- pkg/controllers/clusterresource/keymanagementprovider_controller.go
- pkg/controllers/namespaceresource/keymanagementprovider_controller.go
- pkg/controllers/utils/kmp.go
- pkg/controllers/utils/kmp_test.go
- pkg/keymanagementprovider/azurekeyvault/provider.go
- pkg/keymanagementprovider/azurekeyvault/provider_test.go
- pkg/keymanagementprovider/azurekeyvault/types/types.go
- pkg/keymanagementprovider/keymanagementprovider.go
- pkg/keymanagementprovider/keymanagementprovider_test.go
- pkg/keymanagementprovider/types/types.go
This PR adds an `Enabled` field to the KMPMapyKey struct which allows the provider to store the status of certificates and keys being pulled from the provider into Ratify's KMP. Which is needed to support multiple versions of certificates and keys being stored in the KMP. See discussions and the design doc, [here](https://github.com/ratify-project/ratify/pull/1831), for more details.
Fixes:
- #1751 
- #1831 
```bash
> k describe keymanagementprovider akv
Name:         akv
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  config.ratify.deislabs.io/v1beta1
Kind:         KeyManagementProvider …
```
> feat: support enabled status for kmp keys/certs

- .github/actions/restore_trivy_cache/action.yml
- .github/workflows/e2e-aks.yml
- .github/workflows/e2e-cli.yml
- .github/workflows/e2e-k8s.yml
- .github/workflows/scan-vulns.yaml
- .github/workflows/update-trivy-cache.yml
- Makefile
The trivy DB throttling is getting worse recently. We added retry logic before to mitigate the issue, now we need to cache the DB daily to reduce requests to the trivy DB.
1. Add a new workflow to cache trivy DB dailiy. The `oras pull` command would be retried 10 times with 1 minute interval if it fails.
2. Restore the trivy DB cache for each job that requires trivy scan.
3. Remove retry logic in Makefile.
I've run tests in my forked repo, check status: 
https://github.com/binbin-li/ratify/actions/runs/11705539729
https://github.com/binbin-li/ratify/actions/runs/11705756491
https://github.com/binbin-li/ratify/actions/runs/11705780438
And the update DB job can be only run on dev branch.
Fixes #
Please describe the tests that you ran to verify …
> ci: add cron job to cache trivy db

- go.mod
- go.sum
- pkg/certificateprovider/azurekeyvault/auth.go
- pkg/certificateprovider/azurekeyvault/provider.go
- pkg/certificateprovider/azurekeyvault/provider_test.go
- pkg/keymanagementprovider/azurekeyvault/auth.go
- pkg/keymanagementprovider/azurekeyvault/provider.go
- pkg/keymanagementprovider/azurekeyvault/provider_test.go
- pkg/keymanagementprovider/azurekeyvault/types/types.go
Azure authentication currently uses go-autorest SDK. It's now deprecated and using MSAL and azidentity SDKs are now recommended. This PR replaces the deprecated SDK with azidentity.
Fixes #1630 
[This tutorial](https://ratify.dev/docs/next/quickstarts/ratify-on-azure/#set-up-an-azure-workload-identity) was followed to test authenticating AKS with AKV and retrieval of certificates. 
1- **KeyManagementProvider scenario**: After deploying the following kmp resource using `kubectl apply -f kmp_config.yaml`, the Ratify pod log shows successful retrieval of the certificate.
kmp_config.yaml:
```
apiVersion: config.ratify.deislabs.io/v1beta1
kind: KeyManagementProvider
metadata:
name: keymanagementprovider-akv
spec:
type: azurekeyvault
parameters: …
```
> chore: Replace deprecated autorest SDK with azidentity

- .github/workflows/golangci-lint.yml
- cmd/ratify/cmd/serve.go
- pkg/certificateprovider/certificate_provider_test.go
- pkg/controllers/logging.go
- pkg/keymanagementprovider/keymanagementprovider_test.go
- pkg/manager/manager.go
- pkg/verifier/notation/truststore_test.go
- pkg/verifier/result_test.go
- pkg/verifier/types/types_test.go
There are a bunch of PRs blocking due to unknown golang-ci-lint issue. I tried to bump up the golangci-lint version to unblock it, which works on my forked repo.
This PR bumps up the golangci-lint version and addresses the new linter warnings. I just wonder if we should just pin the version to latest instead.
Fixes #
> chore: bump up golangci-lint version

- RELEASES.md
Fixes release guidance which currently references the wrong github workflow for publishing dev images
Fixes #
> docs: update dev image release guidance

- Makefile
Github is currently in the process of rolling out ubuntu 24.04 as the default runner image for all repositories (now `ubuntu-latest` will point to this version). This version does not have the required `pass` tool installed by default. This PR manually installs `pass` to fix failing tests.
Tested in my own fork with overriding the default runner image to 24.04. Tests now pass: https://github.com/akashsinghal/ratify/actions/runs/12360230974
Fixes #
> build: add manual package installation for pass to support new GH runner image

- charts/ratify/templates/verifier.yaml
- test/bats/base-test.bats
This PR adds an e2e test to ensure that the helm chart template for verifier-notation is rendered properly when custom attributes for notation's trust policies is provided by the user.
Adds e2e test for #1965 
This is an update to the e2e bats file. If the PR succeeds the checks, it means that the test passes.
> chore: add notation-trust-policy e2e test

- pkg/keymanagementprovider/refresh/kubeRefresh_test.go
- pkg/verifier/notation/notationrevocationfactory.go
- pkg/verifier/notation/notationrevocationfactory_test.go
Include a fix in revocationfactory creation. Targeting v1.4.0
Add `sync.Once` to the handler struct instead of a global viable. Fixed creation failure in K8S scenarios.
Fixes #
> fix: update revocation handler creation

- .github/workflows/build-pr.yml
- .github/workflows/e2e-aks.yml
- .github/workflows/e2e-k8s.yml
- .github/workflows/run-full-validation.yml
We need to bump up the Kubernetes versions in the Kubernetes test matrix to 1.30 and 1.31 respectively since v1.29 is no longer maintained by Kubernetes community.
Fixes #1992 
> chore: update workflows according to the latest supported k8s version

- docs/proposals/Release-Supply-Chain-Metadata.md
Update markdown link to the latest available URL
Fixes CI markdown link failure
> chore: update markdown link

- .github/actions/restore_trivy_cache/action.yml
- .github/workflows/update-trivy-cache.yml
All ratify vuln scanning workflows were failing. The cached Trivy db was unable to be restored on workflow start. This is due to a breaking change in the underlying `actions/cache` action. Github is in the process of migrating over to a new v2 backend cache implementation which is requiring a force upgrade of restore action to latest version. 
See: https://github.com/actions/cache?tab=readme-ov-file#%EF%B8%8F-important-changes
Verified on personal fork that it now passes: https://github.com/akashsinghal/ratify/actions/runs/13397689318/job/37420704071
Fixes #
> chore: bump github actions cache to latest version

- .github/workflows/build-pr.yml
- .github/workflows/high-availability.yml
- .github/workflows/quick-start.yml
Remove labeled pull_request_target as it will always triggered CI jobs on labeled PRs.
Fixes #
> ci: remove labeled pull_request_target

- .github/workflows/publish-dev-charts.yml
- .github/workflows/publish-dev-package.yml
- deployments/ratify-gatekeeper-provider/Chart.yaml
- deployments/ratify-gatekeeper-provider/values.yaml
Add pipeline to build and publish chart/image upon merging to main. Each merge will result to an updated ghcr.io/ratify-gatekeeper-provider:dev image and a new chart with version 2.0.0-dev
Fixes #
> ci: build and publish chart/image upon merging to main

- CONTRIBUTING.md
Bridge2Kubernetes  is deprecated an not maintained anymore. Any references to it should be removed from the contributing guide
Fixes #2342
- This change requires a documentation update
> remove references to Bridge2Kubernetes from contributing guide
