README.md

Signed-off-by: Bin Du <bindu@microsoft.com>

minor fix: update the license in readme

---

go.mod
go.sum

Signed-off-by: Sajay Antony <sajaya@microsoft.com>

Update artifacts with mediaType as per v1.0.0-draft.1.1

---

Makefile
README.md
docs/quickstart-cli.md

Signed-off-by: Sajay Antony <sajaya@microsoft.com>

Update to use k8s in readme

---

charts/ratify/Chart.yaml
charts/ratify/templates/deployment.yaml
charts/ratify/values.yaml

Merging release back into main.

Prepare chart for v0.1.1-alpha.1 release (#103)

---

config/config.json

Tested `ratify discover` with both local and remote registries.

Remove useHttp flag

---

README.md

Add the HackMD meeting notes link for the Ratify weekly sync

Add Meeting Notes Link 

---

Makefile
config/config.json
docs/working-with-spdx.md
go.mod
go.sum
plugins/verifier/licensechecker/licensechecker.go
plugins/verifier/licensechecker/utils/spdxutils.go
plugins/verifier/licensechecker/utils/spdxutils_test.go
plugins/verifier/licensechecker/utils/types.go

This is a basic implementation of a license checking verifier that utilizes an SPDX tag-value SBoM

Add licensechecker plugin and docs

---

.github/workflows/build-pr.yml
pkg/utils/certificateUtil_test.go
pkg/utils/certificateUtils.go
plugins/verifier/cosign/cosign.go

- Update GetCertificatesFromPath with null check to handle invalid path
- Added ReplaceHomeShortcut to address issue [78](https://github.com/deislabs/ratify/issues/78)
- Adding more logging to GetCertificatesFromPath

Bug fix and improvement to loading notary verification certs

---

charts/ratify/templates/akv-secret-provider.yaml
charts/ratify/templates/configmap.yaml
charts/ratify/values.yaml

Provide a example where multiple cert can be configured for key vault provider

Update sample configs with multiple cert

---

docs/examples/ratify-on-aws.md
docs/examples/ratify-verify-azure-cmd.md
docs/quickstart-cli.md
docs/working-with-spdx.md

Fixes #227
Updates docs to use new config policy provider config schema
- No test required

updating docs to reflect new policy config

---

README.md

Splitting meeting series into seperate series1 and series2 to accommodate more timezones
- [ X] This change requires a documentation update
N/a

Adding meeting series #1 and #2

---

go.mod
go.sum

Update go-tuf and etcd package to address security alert
- [ X] Bug fix (non-breaking change which fixes an issue)
This will be covered by the e2e test

updating packages to address security fix

---

docs/design/README.md

Adds a design folder with a readme doc with links to hackmd design docs. New docs should be added here accordingly.

Add Design Docs

---

README.md

- [ X] This change requires a documentation update
N/A

consolidating meeting series into single invite

---

docs/examples/ratify-verify-azure-cmd.md

Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>
Fixes #241 
It's just a doc change.

refine ratify-verify-azure-cmd.md and update the installation links

---

.github/workflows/build-pr.yml
Makefile

There seems to be some race conditions with the e2e tests right now failing even though the e2e tests work locally.

Update e2e test dependencies

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

Prepare for 1.1.0 alpha1 release
Ensure E2E test passes

Prepare for 1.1.0-alpha.1 release

---

.gitignore
.vscode/launch.json

Cleans up empty launch.json file in .vscode directory
Git ignores changes to .vscode directory

Cleanup vscode dir

---

Makefile
README.md
docs/examples/ratify-on-aws.md

* Fix gatekeeper-ratify references in Makefile
* Clarify demo instructions, timeout in Readme
* Add deny message text to Readme
* Delete constraint in Readme
Related to #268

Fix and enhance documentation

---

go.mod
go.sum

- Updates ORAS-go to rc2
- Updates artifact spec to rc2
Fixes #259 
Version Upgrade
- builds locally and all unit tests pass
- tested in AKS cluster with private ACR using Azure workload identity and a subject image with single notary signature

Upgrade ORAS-Go and Artifact Spec to RC2

---

README.md

Updates documentation README to note how ratify does not support platform automatic resolution
Fixes #101

Update Documentation For Platform Selection

---

charts/ratify/templates/configmap.yaml

Updates config map AWS auth provider field name

[Bugfix] Fix Configmap AWS Auth Provider Name

---

.github/workflows/scorecards.yml
README.md

Signed-off-by: David Tesar <davete@microsoft.com>
Add openssf scorecard
GitHub workflow
N/A

Add OpenSSF scorecards

---

.github/workflows/release.yml

Adds SBOM to release artifacts using microsoft-sbom tool
N/A

Add SBOM to release

---

.github/workflows/scorecards.yml

Signed-off-by: David Tesar <david.tesar@microsoft.com>

fix openssf versions

---

README.md

Signed-off-by: David Tesar <davete@microsoft.com>
Add goreport badge

add goreport badge

---

.github/workflows/release.yml
.github/workflows/scorecards.yml

Scorecard and SBOM release tools have some challenges.  Verified in my fork now.
https://github.com/dtzar/ratify/actions

Additional GitHub action fixes

---

.github/workflows/build-pr.yml
.github/workflows/release.yml
.goreleaser.yml
go.mod

Signed-off-by: David Tesar <david.tesar@microsoft.com>
Move to latest version of golang and 1.24.6 version for e2e K8s testing.
CI/CD tests pass
N/A

Upgrade to golang 1.19, k8s 1.24.6

---

.github/workflows/codeql.yml

Signed-off-by: David Tesar <david.tesar@microsoft.com>
Add CodeQL to repository

new CodeQL action

---

docs/examples/ratify-verify-azure-cmd.md

Signed-off-by: Binbin Li <libinbin@microsoft.com>
Add missing config for sbom verifier which was deleted mistakenly in https://github.com/deislabs/ratify/pull/357

doc: add missing config

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

Update chart to new release version

---

charts/ratify/templates/serviceaccount.yaml
docs/examples/ratify-verify-azure-cmd.md
docs/oras-auth-provider.md

Signed-off-by: Binbin Li <libinbin@microsoft.com>
1. Update outdated `Azure Workload Identity` section in oras-auth-provider.md
2. Fix charts template.
3. Update ratify-verify-azure-cmd.md. Latest Notation(v0.11.0-alpha.4) is incompatible with Raity of version older than v1.0.0-alpha.3
Run the workload identity setup with AKS successfully.

doc: update doc for workkload identity setup

---

docs/oras-auth-provider.md
docs/quickstart-cli.md
pkg/referrerstore/oras/oras.go

doc: update docs

---

.gitignore
CONTRIBUTING.md
Makefile
charts/ratify/Chart.yaml
charts/ratify/templates/deployment.yaml
charts/ratify/templates/provider.yaml
charts/ratify/templates/secret.yaml
charts/ratify/values.yaml
cmd/ratify/cmd/serve.go
docs/README.md
httpserver/server.go
scripts/generate-tls-certs.sh

- Allow Gatekeeper to connect to Ratify using TLS
- Added new values in values.yaml to support configuring tls/certs/verification
The certificate path and or CA bundle are now passed in when installing Ratify. The certificate can also be loaded from an existing secret if desirable.
Ratify installs now take in new params as follows:
**Option 1**  
Client and server auth disabled
```
helm install ratify ./charts/ratify --atomic
```
**Option 2**  
Client auth disabled and server auth enabled
```
helm install ratify ./charts/ratify \
--set provider.auth="tls" \
--set provider.tls.skipVerify=false \
--set provider.tls.cabundle="$(cat certs/ca.crt | base64 | tr -d '\n\r')" \
--set provider.tls.key="$(cat certs/tls.key)" \
--set provider.tls.crt="$(cat certs/tls.crt)" \
--atomic 
```
**Option …

Allow Gatekeeper to connect to Ratify using TLS

---

deploy/testimages/Dockerfile.signed
deploy/testimages/Dockerfile.unsigned

Removes no longer used test Dockerfile images for sample steps.
- Closes #275

Remove test image Dockerfiles

---

README.md

Signed-off-by: Sajay Antony <sajaya@microsoft.com>
Updates the readme to avoid confusion as a policy engine. Also added a slack link.

docs: Fix readme and add slack link

---

.github/workflows/publish-package.yml
Makefile
charts/ratify/values.yaml

Publish crd image on release

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

Prepare chart to release v1.0.0-beta.1

Prepare for release v1.0.0-beta.1

---

charts/ratify/templates/configmap.yaml
charts/ratify/templates/deployment.yaml
charts/ratify/templates/verifier.yaml
config/config.json
docs/examples/ratify-verify-azure-cmd.md
go.mod
go.sum
pkg/verifier/notaryv2/notaryv2.go
pkg/verifier/notaryv2/notaryv2_test.go

Move trustpolicy from a mounted file to notary verifier config.
Tested locally.

feat: move trustpolicy to verifier config

---

go.mod
go.sum

Bump up notation-go and notation-core-go to rc.1

build: bump up to notation rc.1

---

docs/meeting-notes/ratify-weekly-notes-2021-Jul-2021-Dec.md
docs/meeting-notes/ratify-weekly-notes-2022-Jul-2022-Dec.md

The PR moves the meeting notes into the docs folder so that we can trim the hackmd document and link it here. 
All changes are under the docs folder.

Added meeting notes

---

httpserver/context.go
httpserver/handlers.go
utils/utils.go

Remediates all CodeQL flagged issues. Following PR will fix Open SSF issues.
Fixes #344
- CodeQL vulnerabilities not flagged in personal fork after changes added to main.

Fix CodeQL Issues

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

Prepare for v1.0.0-beta.2 release

Prepare for Beta.2 Release

---

docs/reference/oras-auth-provider.md

document update for msi oras auth provider after pr [#424](https://github.com/deislabs/ratify/pull/424)
Fixes #314

update document of oras auth provider for azure managed identity

---

charts/ratify/templates/deployment.yaml
charts/ratify/values.yaml

Adds the log level value to `values.yaml`. Adds corresponding environment variable in deployment template.

chore: add log level toggle to helm chart

---

Makefile

Pin GK to 3.10.0 until breaking changes are merged in and addressed

pin GK to 3.10.0 until breaking changes are merged in and addressed

---

charts/ratify/templates/store.yaml

fix: store crd chart missing managedIdentity oras authprovider

---

.github/workflows/golangci-lint.yml
.golangci.yml
cmd/ratify/cmd/discover.go
cmd/ratify/cmd/referrer.go
cmd/ratify/cmd/root.go
cmd/ratify/cmd/verify.go
config/configManager.go
httpserver/server_test.go
pkg/controllers/store_controller_test.go
pkg/controllers/verifier_controller_test.go
pkg/referrerstore/oras/oras.go
pkg/utils/certificateUtil_test.go

Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
- Adds workflow for linting
- fixes `errcheck` lint errors
part of #546 

ci: enable linting with golangci-lint

---

.github/workflows/build-pr.yml
.github/workflows/codeql.yml
.github/workflows/golangci-lint.yml
.github/workflows/scorecards.yml

- Updates the workflows to trigger build-pr, codeql, linting, and scorecards on push/PR of release branch
- Branch name must be prefixed with '1.0.0' to count as a release branch
Fixes #

ci: update workflows for release branches

---

.github/workflows/build-pr.yml

Run Azure e2e tests on workflow_dispatch event so that we can trigget it manually on main/rc branch.
Fixes #
Tested on my forked repo. https://github.com/binbin-li/ratify/actions/runs/4035698269

ci:  run Azure e2e tests on workflow_dispatch event

---

charts/ratify/values.yaml

The keyvaultName property has been updated to vaultURI in the latest akv provider
- [ X] Bug fix (non-breaking change which fixes an issue)
Manual test

fix: update chart value for keyvault provider

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

build: prepare for rc1 release

---

charts/ratify/values.yaml

- fixes chart linting error
Fixes #

fix: update values for chart linting

---

.github/workflows/build-pr.yml
.gitignore
Makefile

Add codecov to get the code coverage.
Fixes #

test: add codecov

---

.github/workflows/scorecards.yml

bump up ossf/scorecard-action and actions/upload-artifact to see if it can fix the failing scorecards supply-chain security job.
Fixes #

ci: bump up ossf/scorecard-action and actions/upload-artifact

---

.github/workflows/build-pr.yml

Run build-pr job workflow for each push event so that we'll update the codecov report and test the e2e workflow upon push.
[Fixes #](https://github.com/deislabs/ratify/issues/622)

ci: run build-pr job workflow for each push event

---

Makefile
scripts/azure-ci-test.sh

Enables debug logging for k8 and Azure tests by default to make debugging test failures easier
Fixes #651 

test: enable debug logging for e2e k8 tests

---

go.mod

fix: retract v1.1.0-alpha.1

---

README.md
charts/ratify/Chart.yaml
charts/ratify/values.yaml

Updates chart and README to rc2 release 

chore: prepare for 1.0.0-rc.2 release

---

.github/workflows/publish-package.yml
RELEASES.md

- Adds abbreviated commit SHA to end of the dev build tag
- updates corresponding documentation with new tag format

ci: add commit hash to dev build tag

---

config/config_test.go
pkg/referrerstore/factory/factory_test.go
pkg/referrerstore/oras/mocks/oras_repository.go
pkg/referrerstore/oras/mocks/oras_storage.go
pkg/referrerstore/oras/oras.go
pkg/referrerstore/oras/oras_test.go
pkg/referrerstore/oras/utils_test.go

Adds more unit tests to improve code coverage
Fixes #

test: add more unit tests

---

.github/workflows/build-pr.yml
Makefile
scripts/azure-ci-test.sh
test/bats/azure-test.bats
test/bats/cli-test.bats
test/bats/test.bats

Adds e2e test and accompanying setup to use upstream distribution OCI 1.0 registry to conduct e2e cli validation of OCI fallback. 

test: add oci 1.0 fallback e2e test

---

README.md

Fixes #738 . We need to tell users to update the Helm repos if they have added them before installation. Otherwise, users will install an outdated version of the chart.

doc: add "helm repo update" in README 

---

docs/reference/oras-auth-provider.md

- Updates the k8s secrets auth provider documentation
Fixes #

docs: update k8s secrets auth provider

---

README.md

- updates series 1 to Wed 4:30-5:30pm
Fixes #

docs: update community meeting schedule

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

Updates versions for v1.0.0-rc.4 release

chore: prepare chart for rc4 release

---

.github/workflows/build-pr.yml

Fix failing tests in Azure CI test. The root cause is that the setup-go action has to quote the go-version which is not for now.
Fixes #
Check the Azure tests in my forked repo: https://github.com/binbin-li/ratify/pull/101

fix: fix go version in build-pr.yml

---

docs/reference/crds/certificate-stores.md
docs/reference/crds/stores.md
docs/reference/crds/verifiers.md

Update CRD version from `v1alpha1` to `v1beta1` in doc samples.
Fixes #836 

docs: update CRD version to v1beta1

---

scripts/azure-ci-test.sh

Azure e2e tests are failing since the image built by the test is now the base image without the required external plugin binaries. This PR adds the required build args. 
Fixes #

fix: update Azure build steps

---

Makefile
test/bats/base-test.bats
test/bats/plugin-test.bats

…ages
move cert rotator to plugin test since it will deploy image with plugins
Fixes #

test: move cert rotator to plugin test since it will deploy image with plugins

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

- Prepare chart for rc5 release

chore: update chart for v1.0.0-rc.5

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml

fix: update go releaser to use quoted go version

---

charts/ratify/templates/provider.yaml

fix: helm chart generated cert refers to helm release name in subject

---

README.md

Merging community series #1 and #2
Fixes #

docs: update community meeting to weekly wed

---

.github/workflows/publish-sample.yml

Moving our sample images to ghcr, target path : 
ghcr.io/deislabs/ratify/notary-image:unsigned
Fixes #889
Tested on personal fork

chore: create publish-sample.yml

---

README.md

Adds logo to top of the README
Fixes #

chore: add logo to README

---

.github/workflows/build-pr.yml
Makefile

fix: upgrade notation rc3->rc7

---

Makefile

Reverting this [PR](https://github.com/deislabs/ratify/pull/873) as sbom-tool already fixed the broken release.
Fixes #

build: use latest sbom-tool

---

Makefile

The latest sbom-tool release is missing the assets. Pin to a previous version to unblock pipeline.
Fixes #

build: pin sbom-tool version to v1.2.0

---

api/v1alpha1/policy_types.go
charts/ratify/crds/policy-customresourcedefinition.yaml
config/crd/bases/config.ratify.deislabs.io_policies.yaml

In a previous PR adding Policy CRD, we forgot to rerun the `manifests` and `generate` targets. Now there are unnecessary `deprecated warning` and `v1beta1` field defined in the CRD. This PR is cleaning it up.
Fixes #

fix: fix Policy CRD

---

helmfile.yaml
high-availability.helmfile.yaml

Recent change updated all references of notaryv2 --> notation. This changed the sample notation cert file name. We need to update the helmfile in the quickstart to use this new name.
Fixes #

fix: change name of notation cert file in helmfile

---

terraform/azure/README.md

The link used for Azure document pointed to a different cloud provider.
Fixes #1013 

docs: fix the link for terraform installation

---

charts/ratify/templates/assign.yaml
library/default/template.yaml
library/notation-issuer-validation/template.yaml
library/notation-validation/template.yml
library/sbom-validation/template.yaml

Added `initContainers`, `ephemeralContainers` into current constraint templates
Fixes #950 
E2E Test will be post later and linked with another issue
All tests have passed
create `myapp.yaml`
log from ratify
Debugging with an ephemeral debug container
log from ratify

chore: update  constraint templates

---

go.mod
go.sum

Fixes #1047
upgrade oras-go v2.3.0

feat: upgrade oras-go v2.3.0

---

README.md

Add a badge linking to pkg.go.dev: https://pkg.go.dev/github.com/deislabs/ratify
Fixes #

docs: add badge linking to pkg.go.dev

---

scripts/azure-ci-test.sh

Fixes #
azure test could be checked on my forked branch: https://github.com/binbin-li/ratify/pull/108

fix: fix azure test

---

dev.helmfile.yaml
dev.high-availability.helmfile.yaml
helmfile.yaml

Helmfile needs to point to latest release
Fixes #
- [ X] Bug fix (non-breaking change which fixes an issue)

fix: update helmfile.yaml for rc8

---

Makefile
test/bats/base-test.bats
test/testdata/pod_initContainers_signed.yaml
test/testdata/pod_initContainers_unsigned.yaml

fix: update e2e resource for initContainers and ephemeralContainers

---

helmfile.yaml
high-availability.helmfile.yaml

chore: bump helmfile versions to match v1.0 chart released

---

README.md

docs: remove non production notice

---

artifacthub-repo.yml

Add repo owners to make Ratify labeled as Verified Publisher.
Resolving: https://github.com/deislabs/ratify/issues/426
Fixes #

chore: add repo owners

---

docs/README.md
docs/design/Config Policy Provider Refactor.md
docs/design/Ratify Error Refactor.md
docs/design/Verification Result Cache at Executor Level.md

docs: add design docs

---

pkg/verifier/notation/notation.go

Addressing feedback from @yizha1 that plugin init error didn't include nested error from notation-go when init a notation verifier.
Fixes #

chore: wrap notation-go error

---

.github/workflows/cache-cleanup.yml

- adds recommended workflow to manually delete GH action cache keys for feature branches once PR is closed.
Fixes #1241 

ci: add cache cleanup post merge

---

httpserver/handlers.go

chore: rename func for readability

---

api/unversioned/store_types.go
api/unversioned/verifier_types.go
api/v1alpha1/store_conversion.go
api/v1alpha1/verifier_conversion.go
api/v1alpha1/zz_generated.conversion.go
api/v1beta1/zz_generated.conversion.go
config/crd/bases/config.ratify.deislabs.io_stores.yaml
config/crd/bases/config.ratify.deislabs.io_verifiers.yaml
pkg/controllers/store_controller_test.go
pkg/controllers/verifier_controller_test.go

1. Add version and status fields to unversioned store and verifier.
2. Add missing conversion methods to `alpha1` verifier and store.
3. Fix failing unit tests by creating test plugins in a temporary directory.
The unit tests only failed during local development on VS Code since we don't install those plugins under required path.
Fixes #

fix: add missing CRD conversion methods

---

Makefile

- the localhost:5000 test registry reference was accidentally hard coded in the sbom generation setup target. This PR updates the reference to use the variable.
Fixes #

fix: update hard coded test registry reference

---

.devcontainer/Dockerfile

update the image tag from `0-1.21-bullseye` to `1.21-bullseye`
Fixes #

chore: update the image tag of dev container

---

.github/licenserc.yml

- after a recent update of a package version, the version in the licenserc.yaml file is out of date causing failure
Fixes #

ci: update license check exclusion version

---

.github/workflows/build-pr.yml
.github/workflows/e2e-aks.yml
.github/workflows/e2e-cli.yml
.github/workflows/e2e-k8s.yml
.github/workflows/pr-to-main.yml
.github/workflows/run-full-validation.yml
CONTRIBUTING.md

This is a recreated PR of  https://github.com/deislabs/ratify/pull/1353 
build-pr.yml -> run basic test matrix, full matrix can be trigger with "safe to test" tag.
pr-to-main.yml -> on push to staging, open a PR with the commit title against main branch
run-full-validation.yml -> triggers full validation including cloud specific tests on pull request to the main branch.
Fixes #1249
- Tested on my local fork.
here are the sample PR with sequence of action.
Dev opens a PR from "myBranch" to staging
https://github.com/susanshi/ratify/pull/283
Test passes and Maintainer approves the PR
Dev/Maintainer merges the PR with …

feat: run full validation on staging

---

README.md

fix: updated community meeting time to UTC

---

.github/workflows/e2e-cli.yml
.github/workflows/pr-to-main.yml
README.md
go.mod
go.sum

chore: Bump actions/checkout from 4.1.1 to 4.1.2

---

.github/workflows/e2e-cli.yml
.github/workflows/pr-to-main.yml
README.md
ROADMAP.md
go.mod
go.sum

docs: add roadmap

---

.github/workflows/e2e-cli.yml

Add cocdecov tokenso that codecov CLI could upload reports. Currently we only have PR uploading reports which don't require the token. But once we want to display the coverage for the main/dev branches, it will be required.
https://docs.codecov.com/docs/frequently-asked-questions#where-is-the-repository-upload-token-found
Fixes #

build: Add codecov token

---

.github/workflows/e2e-cli.yml

build: Add codecov token (#1373)

---

.github/workflows/cache-cleanup.yml
.github/workflows/e2e-aks.yml
.github/workflows/e2e-cli.yml
.github/workflows/e2e-k8s.yml
.github/workflows/quick-start.yml

fix: add top-level read permission

---

plugins/verifier/sbom/testdata/osv-scanner.toml
plugins/verifier/schemavalidator/schemavalidation/testdata/osv-scanner.toml
plugins/verifier/vulnerabilityreport/schemavalidation/testdata/osv-scanner.toml
test/testdata/osv-scanner.toml

Add osv-scanner.toml under each directory that includes test json file containing busybox image. Since it's just test data which will not impact Ratify security, we can ignore it via osv-scanner.toml, like https://github.com/google/osv-scanner/blob/d75f136bbfdfd952d770dda15a94e0d9ef6c9a42/cmd/osv-scanner/fixtures/locks-many/osv-scanner.toml#L7 in osv-scanner repo.
Tested in my forked repo which resolved the security issue.
Fixes #

build: ignore CVE-2022-48174

---

.devcontainer/Dockerfile
.github/dependabot.yml
crd.Dockerfile
httpserver/Dockerfile

1. Added digest for unpinned images.
2. Added dependabot check for Dockerfile to upgrade images weekly.
I'm not sure if I should ignore golang version as we manually maintain and upgrade it though we can use `@dependabot ignore` command in the future.
I tested on my forked repo which will resolved related security issues.
And for issues like https://github.com/deislabs/ratify/security/code-scanning/60, since `go install` command only works with `path@version`, I feel we can just dismiss the alert.
Fixes #

build: fix unpinned images

---

.github/workflows/run-full-validation.yml

Remove pull_request_target trigger so that dependabot PRs will not trigger it as it's always labeled.
Fixes #

fix: check label value on pull_request_target

---

dev.helmfile.yaml
dev.high-availability.helmfile.yaml

New namespaced resources were introduced as part of multi-tenancy work. dev helmfiles should be updated to clean up these resource definitions. 
Fixes #

chore: update dev helmfiles to clean up namespaced resources

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml

chore: prepare for release 1.2-rc.1

---

.github/workflows/e2e-aks.yml
.github/workflows/run-full-validation.yml

We should run full validation on release branch
Fixes #
- [X ] Bug fix (non-breaking change which fixes an issue)
e2e

fix: full validation should run on release branch

---

.github/codecov.yml

Set patch coverage target to 80%
Fixes #

ci: set patch coverage target to 80%

---

.github/workflows/scorecards.yml

Run the scorecard on PRs merging to dev/main so that we can block vulnerabilities in PRs.
Fixes #

ci: run scorecard on pr to dev/main

---

.github/workflows/clean-dev-package.yml

1. Move write package permission under job level.
2. Pin the version by hash tag.
Fixes #

fix: fix vulnerabilities

---

ROADMAP.md

Refresh roadmap after v1.2.0 release

chore: refresh roadmap after v1.2.0 release

---

README.md
index.yaml

chore: update deislabs.github.io to ratify-project.github.io

---

.github/workflows/publish-dev-assets.yml
dev.helmfile.yaml
dev.high-availability.helmfile.yaml

- changes dev publishing assets to point to ratify-project
Fixes #

chore: update dev helmfile and publishing workflow

---

README.md

update README code of conduct to align with content in CODE_OF_CONDUCT.md
Fixes #

doc: update README code of conduct

---

SECURITY.md

Reset Ratify security.md to direct customer to use github for vuln reports
Fixes #

doc: Update SECURITY.md

---

.github/workflows/scan-vulns.yaml
Makefile

Cherry picked all commits related to scanner at https://github.com/ratify-project/ratify/commits/dev/.github/workflows/scan-vulns.yaml
Fixes #

chore: cherry pick vuln scanner to release 1.2

---

Makefile

A makefile change splited from ##1538
This is an enhancement change

chore: update a flag in makefile

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

prepare release 1.2.1 charts update

chore: prepare release 1.2.1 charts update

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

chore: prepare release 1.2.1 charts update 2

---

helmfile.yaml
high-availability.helmfile.yaml

chore: prepare release 1.2.1 helmfile update

---

archive/meeting-notes/ratify-weekly-notes-2023-Jun-2024-Jun.md

doc: meeting notes ratify-weekly-notes-2023-Jun-2024-Jun.md

---

docs/design/kmp-periodic-retrieval.md

This proposal suggests automating the update process of KMP resources in Ratify.

docs: design doc for KMP periodic retrieval 

---

docs/design/Config Policy Provider Refactor.md
library/default/template.yaml
library/multi-tenancy-validation/template.yaml
library/notation-issuer-validation/template.yaml
library/notation-nested-validation/template.yaml

Per the suggestion from @yizha1, update the failure verification result from `Subject failed verification:` to `Failed to verify the artifact` for better clarity.
Screenshot before change:
Screenshot after change:
Fixes #

chore: rephrase failure result in constraint template

---

.github/workflows/e2e-cli.yml

Fix a type by removing duplicate $
Fixes #

fix: remove duplicate $

---

pkg/verifier/notation/notation.go

fix a typo in notation verifier
Fixes #

fix: fix typo in notation verifier

---

go.mod
go.sum

Fix security issue GO-2024-3005
Fixes # [Authz zero length regression · CVE-2024-41110 · GitHub Advisory Database](https://github.com/advisories/GHSA-v23v-6jw2-98fq)

fix: bump-up docker dependency

---

.github/workflows/scorecards.yml

Fixes #1686 
PRs to release branch would trigger the Scorecards action

chore: update scorecards action

---

go.mod
pkg/certificateprovider/azurekeyvault/auth.go
pkg/keymanagementprovider/azurekeyvault/auth.go

This pr just removed unused code path referencing `github.com/Azure/go-autorest/autorest/adal` module. It will change the module to an indirect dependency.
Fixes #

chore: remove unused code path

---

go.mod
go.sum

Fixes #1686
local branch test: https://github.com/junczhu/ratify/pull/1

chore: Release 1.2.2 vuln bump-up

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Release 1.2.2 helm chart update

chore: release 1.2.2 helm chart update

---

README.md

Add the governance doc link to the `readme.md` per the suggestion on https://github.com/cncf/sandbox/issues/96#issuecomment-2289735908

chore: add the governance doc link to readme.md

---

library/default/template.yaml

This is a follow-up PR for https://github.com/ratify-project/ratify/pull/1697
We've added timestamp and traceId to the constraint template in dev branch, however, the template in [quick start](https://ratify.dev/docs/next/quickstarts/quickstart-manual#step-3-see-ratify-in-action) is defined in `gh-pages` branch.
Fixes #

chore: update default constraint template

---

pkg/certificateprovider/azurekeyvault/provider_test.go
pkg/keymanagementprovider/azurekeyvault/provider.go
pkg/keymanagementprovider/azurekeyvault/provider_test.go

Add tests to AKV provider to cover negative cases.
Fixes #

test: add tests to akv provider

---

charts/ratify/values.yaml

Fixes an app version in charts.

chore: update local dev charts to the latest version

---

pkg/verifier/notation/truststore_test.go

fix: tsa test fix

---

pkg/verifier/notation/notation_test.go

Add more unit test and improve test coverage in the notation.go

test: add unit test for notation.go

---

.github/workflows/build-pr.yml
.github/workflows/run-full-validation.yml

Fixes AKS e2e ci
Tests result from fork:

chore: update aks version

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Update helmcharts for release 1.3.0 for quick_start validation that requires the latest helmfile changes in dev branch.

chore: update helm charts for v1.3.0

---

README.md

As we just published Ratify v1.3.0, the package path on pkg.go.dev is updated to `ratify-project/ratify` instead of `deislabs/ratify`. This PR updates the go reference badge accordingly.
Fixes #

chore: update go reference badge to the new path

---

CONTRIBUTING.md

PR contains the below changes to the contributing guide
1.added table of content
2.added a section for Commits ( verbiage from notary project)
3.add a youtube link for vscode debug recording

docs: add commits doc to contributing guide

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Patch release fixes tagging in publish-ghcr workflow 
Including Cherry-pick https://github.com/ratify-project/ratify/pull/1884 https://github.com/ratify-project/ratify/pull/1854 https://github.com/ratify-project/ratify/pull/1819

chore: release-1.3.1 charts

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

chore: update charts

---

.github/workflows/update-trivy-cache.yml

A quick fix to compare the correct ref_name instead of ref, otherwise the job would be skipped.
Tested in my forked repo:
Fixes #

fix: fix the conditional check on update-trivy-cache job

---

.github/workflows/publish-dev-assets.yml
.github/workflows/publish-package.yml
.well-known/pki-validation/trustpolicy.json

This PR adds release image signing using Notation and Cosign for all release images: `ghcr.io/ratify-project/ratify`, `ghcr.io/ratify-project/ratify-crds`, `ghcr.io/ratify-project/ratify-base`. The next minor version release `v1.4.0` will utilize the new signing workflow.
Doc update PR: https://github.com/ratify-project/ratify-web/pull/129/files
Sample workflow showing release flow successful: https://github.com/akashsinghal/ratify/actions/runs/11963756788/job/33354797232
Cosign signature attached: 
Notary Project signature attached: 
Fixes #1437

build: add image signing for all release images

---

CONTRIBUTING.md

docs: Fix typos in CONTRIBUTING.md

---

test/bats/cli-test.bats
test/bats/helpers.bash

further improve crl e2e test script
Previously test cases depend on the server changes to provide a CRL sample.
Update test case via manage local files to set up test CRL.
Fixes # NA

test: update test script

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Chart changes for Ratify 1.4.0-rc.1

chore: release chart for Ratify 1.4.0-rc.1

---

charts/ratify/templates/configmap.yaml

Update `configmap.yaml` to enable reading from `value.yaml` and holding a default value.
Fix helm chart value setting
Manual test results:
1. update with `--set value`
2. read value from `value.yaml`

fix: update configmap

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Prepare release charts for v1.4.0-rc.1

chore: update release charts 1.4.0-rc.1

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Apply 1.4.0-rc.1 chart updates to dev branch
Manual Test Result:

chore: update charts 1.4.0-rc.1

---

.github/crd.trivyignore.yaml
.github/workflows/scan-vulns.yaml

The Trivy scanning job is failing due to a HIGH severity in the `kubectl` binary built in CRD image. Kubernetes maintainers have acknowledged K8s is not affected by it but will bump the version in the next release (v1.33). In mean time, Ratify will need to suppress this CVE for CRD image
- adds a new `crd.trivyignore.yaml` file with the particular CVE to be suppressed and a reason for why
- updates scanning workflow to use trivyignore yaml
- bumps trivy version to latest which includes new ignore support
Validated here: https://github.com/akashsinghal/ratify/actions/runs/12795805864/job/35673995673
Fixes #

ci: suppress false-positive CVE in CRD image scanner

---

archive/meeting-notes/ratify-weekly-notes-2024-Jun-2024-Dec.md

Archiving meeting notes
Fixes #
Doc change only
archive meeting notes. No testing required

chore: meeting notes ratify-weekly-notes-2024-Jun-2024-Dec.md

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Update versions for v1.4.0
Fixes #

chore: update release charts for v1.4.0

---

pkg/common/oras/authprovider/azure/const.go
pkg/common/oras/authprovider/azure/helper.go

Add some ACR endpoints.
Fixes #

chore: add more acr endpoints

---

pkg/common/oras/authprovider/azure/const.go
pkg/common/oras/authprovider/azure/helper.go

chore: add more acr endpoints (#2079)

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

- updates chart version to 1.14.2
- updates tag version to v1.3.2
- updates helmfiles
Fixes #

chore: bump chart versions for v1.3.2

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

- update helm chart version to 1.13.4 (NOTE: patch version discrepancy is expected due to previous release issue)
- update tag version to v1.2.3
- update helmfiles
Fixes #

chore: bump chart versions for v1.2.3

---

go.mod
go.sum

- Updates ristretto package to a new version that removes a vulnerable dependency
Fixes #

chore: bump ristretto pkg version

---

go.mod
go.sum

Cherry picks #2085 into release branch
Fixes #

chore: bump ristretto pkg version (#2085)

---

charts/ratify/Chart.yaml
charts/ratify/values.yaml
helmfile.yaml
high-availability.helmfile.yaml

Update release chart in dev branch

chore: update dev chart

---

pkg/utils/azureauth/authenticationUtils.go

- Removes the unnecessary `oauth2/token` in the authority host URL passed to the confidential client creation method
- Update to the MSAL go library from 1.2.3 to 1.3.2 caused a breaking change in how the authority host URL is parsed
In the existing implementation, which Ratify has now had for 2 years in the workload identity auth provider, Ratify passes in a specific authority host for which the MSAL SDK creates a client. This authority host consists of the authority which is injected as an environment variable by the workload identity controller in AKS and the tenant ID. Ratify also appends the `/oauth2/token` at the at the end of authority URL. The workload identity azure workload identity guide for MSAL previously had this `oauth2/token` suffix in their example. This was …

fix: update Azure authentication utility method to provide correct authority host

---

docs/proposals/Enhancement-Proposal-Template.md

A Ratify Enhancement Proposal (REP) is a way to propose, communicate and coordinate on new features and enhancements for the Ratify project.
This PR adds a Ratify Enhancement Proposal Template to provide a consistent format for proposing new features and improvements, ensures contributors follow a structured approach, making it easier for maintainers to review proposals.
This is a common practice that a few mature communities like Kubernetes are applying https://github.com/kubernetes/enhancements/blob/master/keps/README.md
Fixes #https://github.com/ratify-project/ratify/issues/2121

docs: add Ratify Enhancement Proposal Template

---

README.md

This is a minor change to update the meeting inforamtion in the README file

docs: update meeting inforamtion in README

---

.github/workflows/golangci-lint.yml
.golangci.yml
api/v1alpha1/policy_conversion.go
api/v1alpha1/policy_conversion_test.go
errors/types.go
httpserver/tlsManager.go
pkg/cache/dapr/dapr.go
pkg/common/oras/authprovider/azure/azureworkloadidentity_test.go
pkg/common/plugin/download.go
pkg/common/plugin/exec.go
pkg/controllers/clusterresource/keymanagementprovider_controller_test.go
pkg/controllers/clusterresource/store_controller_test.go
pkg/controllers/namespaceresource/certificatestore_controller.go
pkg/controllers/namespaceresource/keymanagementprovider_controller.go
pkg/controllers/namespaceresource/keymanagementprovider_controller_test.go
pkg/customresources/certificatestores/certificatestores.go
pkg/executor/core/executor_test.go
pkg/keymanagementprovider/azurekeyvault/provider_test.go
pkg/policyprovider/factory/factory.go
pkg/referrerstore/oras/cache_test.go
pkg/referrerstore/oras/oras.go
pkg/referrerstore/oras/utils_test.go
pkg/utils/utils.go
pkg/verifier/cosign/trustpolicy.go
plugins/verifier/sbom/sbom.go
plugins/verifier/schemavalidator/schema_validator.go
plugins/verifier/vulnerabilityreport/vulnerability_report.go
utils/utils.go

1. Upgrade golangci-lint-action to v7
2. Executed golangci-lint migrate to migrate the configuration
3. Fix warnings raised by linter.
Fixes #

chore: Bump golangci/golangci-lint-action from 6.5.2 to 7.0.0

---

.github/workflows/build-pr.yml
.github/workflows/codeql.yml
.github/workflows/golangci-lint.yml
.github/workflows/high-availability.yml
.github/workflows/pr-to-main.yml
.github/workflows/quick-start.yml
.github/workflows/run-full-validation.yml
.github/workflows/scorecards.yml

We just created new branch `v1` based on `main` and `v1-dev` based on `dev`. Now the default branch is switched to `main`, some CIs are failing due to incompatible setup. This PR will address broken CIs and pin some CIs to `v1` only like the AKS test.
Fixes #

fix: fix broken pipelines after switching default branch to main

---

README.md

Add a warning notice for community members to be aware of the v2 development on main branch.
Fixes #

docs: add v2 development notice

---

go.mod
go.sum
pkg/keymanagementprovider/azurekeyvault/provider.go
pkg/keymanagementprovider/azurekeyvault/provider_test.go
pkg/keymanagementprovider/refresh/kubeRefresh.go
pkg/keymanagementprovider/refresh/kubeRefresh_test.go

1. Update module to v2 from v1.
2. Some new updated were not released in v1 branch, update import path to v2 as a workaround to avoid broken build.
Fixes #

build!: init ratify v2

---

ROADMAP.md

Prev [PR](https://github.com/ratify-project/ratify/pull/2173) was merging to `dev` branch, this PR copies the same updates to `main` branch.
Fixes #

docs: add v2 roadmap

---

Makefile

fix: add .gotmpl to helmfile in Makefile

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
.github/workflows/check-license.yml
.github/workflows/high-availability.yml
.github/workflows/markdown-link-check.yml

1. Add license checker job.
2. Add Markdown-link check job.
3. Add job to run unit test and upload to Codecov.
4. Stop running high-avaliablity test on main.
Tested in my forked repo:
Fixes #

ci: add CIs running on main branch

---

.github/workflows/golangci-lint.yml

Bump up golangci-lint version.
Fixes #

ci: bump up golangci-lint version

---

.github/workflows/run-full-validation.yml
deployments/ratify-gatekeeper-provider/Chart.yaml

Set run-full-validation job runs only on release-1.* branch.
Fixes #

ci: Disable full validation for release-2. branch*

---

.well-known/pki-validation/trustpolicy.json

Update registryScope during notation verification when publishing to ghcr.
Fixes #

fix: update registryScope for asset verification

---

.github/workflows/build.yml

Add workflow_dispatch to build job so that it can be triggered manually.
Fixes #

ci: add workflow_dispatch to build job

---

.github/workflows/build-pr.yml
.github/workflows/codeql.yml
.github/workflows/golangci-lint.yml
.github/workflows/high-availability.yml
.github/workflows/quick-start.yml
.github/workflows/run-full-validation.yml
.github/workflows/scorecards.yml

This PR updates the GitHub Actions workflow to exclude running on pull requests that contain documentation-only changes. This improves CI efficiency by avoiding unnecessary workflow runs for non-code updates.
Fixes #

chore(ci): update PR workflows to exclude .md files

---

internal/cache/api.go
internal/cache/inmemory/inmemory.go
internal/cache/inmemory/inmemory_test.go
internal/cache/ristretto/ristretto.go
internal/cache/ristretto/ristretto_test.go
internal/httpserver/handlers.go
internal/httpserver/handlers_test.go
internal/httpserver/server.go
internal/store/credentialprovider/azure/register.go
internal/store/credentialprovider/azure/register_test.go
internal/store/credentialprovider/cachedprovider.go
internal/store/credentialprovider/cachedprovider_test.go
internal/store/credentialprovider/static/register.go
internal/store/credentialprovider/static/register_test.go

1. Refactor the cache interface to use generics and add a ttl parameter to the Set method.
2. Add a simple inmemory cache implementation based on map and Mutex.
3. Add a `CredentialSourceProvider` interface to define a GetWithTTL method which returns a credential with its ttl.
4. Update azureCredentialProvider to implement the `CredentialSourceProvider` interface.
5. Add a `CachedProvider` struct to wrap up `CredentialSourceProvider` implementation and cache which will cache the credential with its ttl.
6. Keep staticProvider using uncached credentials.
Fixes #
Added unit test and added info logs in e2e test to validate cache is hit or missed.

feat: add cache to registry token

---

internal/policyenforcer/threshold/parse.go
internal/policyenforcer/threshold/parse_test.go

Fix error when parsing policy rule as the underlying type is actually []any instead of []map[string]any.
Fixes #
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Helm chart change (any edit/addition/update that is necessary for changes merged to the `main` branch)
- This change requires a documentation update

fix: fix parsing policy error

---

internal/policyenforcer/threshold/parse.go
internal/policyenforcer/threshold/parse_test.go

The numeric value from json is parsed to float64 by default, we need to do another conversion from float64 to int.
Fixes #
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Helm chart change (any edit/addition/update that is necessary for changes merged to the `main` branch)
- This change requires a documentation update

fix: fix parsing numeric value from json

---

internal/controller/executor_controller_test.go
internal/controller/executormanager.go
internal/controller/executormanager_test.go
internal/executor/executor.go
internal/executor/executor_test.go
internal/httpserver/config/config.go
internal/httpserver/config/config_test.go
internal/httpserver/server_test.go
internal/policyenforcer/factory.go
internal/policyenforcer/factory_test.go
internal/store/factory.go
internal/store/factory_test.go
internal/store/filesystemocistore/register.go
internal/store/filesystemocistore/register_test.go
internal/store/registrystore/register.go
internal/store/registrystore/register_test.go
internal/verifier/cosign/register.go
internal/verifier/cosign/register_test.go
internal/verifier/factory.go
internal/verifier/factory_test.go
internal/verifier/notation/register.go
internal/verifier/notation/register_test.go

1. Refactor factory names.
2. Refactor factories to use options value instead of pointer.
Unit test updated.

refactor: refactor naming and pointers

---

.github/codecov.yml

Update project coverage target to 75%.

ci: update project coverage target
